# Generated by Django 3.0.4 on 2020-05-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mcdo',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50)),
                ('dop', models.DateTimeField(db_column='DOP')),
                ('content', models.TextField()),
                ('doa', models.DateTimeField(blank=True, db_column='DOA', null=True)),
                ('approval_from', models.IntegerField()),
            ],
            options={
                'db_table': 'mcdo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='McdoLogs',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('approval_from', models.IntegerField()),
            ],
            options={
                'db_table': 'mcdo_logs',
                'managed': False,
            },
        ),
    ]
